# backend/services/knowledge_base.py
import re

QA_DATA = [
    # --- Platform Overview & Vision (1–50) ---
    {"q": "What is Astira?", "a": "Astira is an NFT creation and trading platform built around the theme of 'planets,' where users generate, mint, display, trade, and operate their own planet NFTs."},
    {"q": "What kind of narrative framework does Astira use?", "a": "A unified cosmic narrative framework."},
    {"q": "What traditional NFT market model does Astira reject?", "a": "The 'uploading images – listing – buying and selling' model."},
    {"q": "What three main problems does Astira aim to solve?", "a": "NFTs lacking continuous interaction, lacking a worldview, and lacking long-term participation incentives."},
    {"q": "What is Astira's core positioning in one sentence?", "a": "Lowering the threshold for creation with AI, enhancing asset vitality through on-chain evolution, increasing user engagement with a social star map, and supporting long-term ecological expansion with DAO and public chain plans."},
    {"q": "How does Astira describe its one-sentence summary?", "a": "It is not a platform for selling planet images, but rather helps users map their 'ideals and identities' into a digital planet that can be created, owned, traded, evolved, and governed."},
    {"q": "What is Astira's vision?", "a": "Create a digital universe where everyone can showcase their art, with each planet carrying an individual's aesthetics, stories, identities, and value propositions."},
    {"q": "What is Astira's mission (first point)?", "a": "Lower the barriers to high-quality NFT creation."},
    {"q": "What is the second part of Astira's mission?", "a": "Transform NFTs from static collectibles into dynamic assets."},
    {"q": "What is the third part of Astira's mission?", "a": "Establish a long-term ecosystem that balances creation, trading, interaction, and governance."},
    {"q": "What is the fourth part of Astira's mission?", "a": "Gradually transition to self-owned blockchain infrastructure."},
    {"q": "Who are Astira's target users?", "a": "NFT collectors, Web3 users, digital art creators, astronomy enthusiasts, young communities, and ordinary users who wish to participate in new forms of digital identity expression."},
    {"q": "What is the emotional core of Astira?", "a": "Not pure financial speculation, but rather 'creating a planet of one's own,' emphasizing dreams, long-termism, identity expression, and a sense of participation."},
    {"q": "What is the first market pain point Astira addresses?", "a": "Static NFT assets that are only lively during minting and lack evolution mechanisms."},
    {"q": "What is the second market pain point?", "a": "High barriers to creation, where high-quality NFTs require designers, modelers, and developers."},
    {"q": "What is the third market pain point?", "a": "Lack of narrative containers in the market – only trading pages without story spaces or immersive displays."},
    {"q": "What opportunity does Astira see in the market?", "a": "A platform that simultaneously features low-barrier creation, continuous evolution, trading liquidity, social display, and a unified worldview becomes a scalable universe product layer."},
    {"q": "How does Astira describe its brand emotion?", "a": "Dreams, long-termism, identity expression, and a sense of participation."},
    {"q": "Is Astira only for professional NFT creators?", "a": "No, it lowers the barrier so ordinary users can also create."},
    {"q": "Does Astira focus only on trading?", "a": "No, it focuses on creation, evolution, social interaction, and governance as well."},
    {"q": "What type of digital asset does Astira use?", "a": "Planet NFTs."},
    {"q": "Does Astira have its own blockchain?", "a": "Not initially, but it has a public chain plan (Astira Chain) for later phases."},
    {"q": "What is the ultimate goal of Astira?", "a": "To become a long-term Web3 brand with cultural attributes and an economic system."},
    {"q": "How does Astira define its product?", "a": "As a 'cosmic creation tool' rather than just a marketplace."},
    {"q": "What does Astira want users to feel?", "a": "A sense of 'I belong here.'"},
    {"q": "Does Astira allow user governance?", "a": "Yes, through DAO and the Planetary Council."},
    {"q": "Is Astira a metaverse project?", "a": "It is a lightweight cosmic space, not a heavy metaverse."},
    {"q": "Does Astira compete with traditional NFT marketplaces?", "a": "It differentiates by adding evolution, narrative, and social features."},
    {"q": "What type of NFT evolution does Astira offer?", "a": "Dynamic NFTs that change over time, behavior, and on-chain events."},
    {"q": "Can users create planets without coding?", "a": "Yes, using natural language description and AI generation."},
    {"q": "Does Astira support 3D planet visuals?", "a": "Yes, AI generates both 2D and 3D visual drafts."},
    {"q": "What is the 'Original Planet Series'?", "a": "16 original planets that serve as the aesthetic ancestors and value source for all new planets."},
    {"q": "Do original series holders get royalties?", "a": "Yes, when a new planet is generated based on their series branch, they receive a portion of royalties."},
    {"q": "Can planets be merged?", "a": "Yes, through the integration mechanism."},
    {"q": "Can planets be broken apart?", "a": "Yes, through deconstruction into resource fragments."},
    {"q": "Does Astira use real astronomical data?", "a": "Yes, from NASA, ESA, and other public databases."},
    {"q": "What is the $AST token used for?", "a": "Payments, incentives, governance, and ecosystem settlement."},
    {"q": "Is $AST an investment-only token?", "a": "No, it has functional uses like paying minting fees, governance, staking, etc."},
    {"q": "What chains will Astira initially deploy on?", "a": "Low-gas, user-friendly chains like Solana."},
    {"q": "Does Astira have a DAO?", "a": "Yes, with governance rights for original series holders, qualified planet holders, and AST holders."},
    {"q": "What is the Planetary Council?", "a": "The later-stage community-driven governance body."},
    {"q": "How does Astira generate revenue?", "a": "Transaction fees, AI premium services, minting/function fees, brand partnerships."},
    {"q": "What is the roadmap's first phase?", "a": "Platform validation – brand, core visuals, MVP creation, basic trading."},
    {"q": "What is the second phase?", "a": "Gameplay enhancement – dynamic evolution, star map, user logs, airdrops."},
    {"q": "What is the third phase?", "a": "Ecological expansion – integration/disassembly, brand collabs, DAO proposals."},
    {"q": "What is the fourth phase?", "a": "Infrastructure upgrade – Astira Chain, cross-chain, developer interfaces."},
    {"q": "Does Astira have a lightweight map design?", "a": "Yes, 2D/light 3D to avoid heavy metaverse costs."},
    {"q": "Can users visit other people's planets?", "a": "Yes, via the galaxy map."},
    {"q": "What can users see on another planet's page?", "a": "Logs, stories, showcase content, live content, activity records."},
    {"q": "What is the final assertion of the whitepaper?", "a": "Everyone who runs for their ideals deserves to have a planet of their own in the digital universe. Astira is the starting point."},

    # --- AI-Driven Planet Genesis (51–100) ---
    {"q": "How do users create a planet on Astira?", "a": "By describing it through natural language input (color, terrain, rings, resources, story tags)."},
    {"q": "What does the AI generate from the description?", "a": "2D/3D visual drafts and structured attributes."},
    {"q": "Are the AI outputs completely random?", "a": "No, they inherit the visual genes and cosmic grammar of the original planet series."},
    {"q": "What attributes does the system output for a planet?", "a": "Name, visual form, rarity, resource type, habitability index, special event triggers, cosmic coordinates, family lineage."},
    {"q": "Why does Astira constrain AI generation?", "a": "To avoid content overflow and aesthetic loss of control."},
    {"q": "How does Astira ensure new planets relate to the original series?", "a": "Through a gene inheritance mechanism – color system, structural characteristics, climate elements, resource tags, or thematic emotions."},
    {"q": "What is the value significance of the AI generation system?", "a": "Astira upgrades from a trading market to a cosmic creation tool."},
    {"q": "Is the AI generation free for all users?", "a": "Basic preview is free; premium generation (higher precision, richer styles, more edits) is a paid service."},
    {"q": "Can users edit planets after generation?", "a": "Yes, with premium services allowing more editing opportunities."},
    {"q": "Does the AI generate only visual images?", "a": "No, it generates a complete set of chainable planet definitions."},
    {"q": "What is a 'chainable' planet definition?", "a": "Data that can be minted as an NFT with on-chain attributes."},
    {"q": "Does the AI consider user story tags?", "a": "Yes, story tags are part of the input."},
    {"q": "How does Astira maintain artistic consistency across all planets?", "a": "By having a unified artistic style constraint and inheritance from the original series."},
    {"q": "Can the AI generate rare planets?", "a": "Yes, rarity is one of the output attributes."},
    {"q": "What is a 'habitability index'?", "a": "An attribute output by the AI indicating how habitable the planet is."},
    {"q": "What are 'special event triggers'?", "a": "Conditions that cause on-chain events to affect the planet."},
    {"q": "What are 'cosmic coordinates'?", "a": "A location identifier for the planet in the galaxy map."},
    {"q": "What is 'family lineage' in planet generation?", "a": "Which original planet series the new planet is descended from."},
    {"q": "Does the AI support real astronomical parameter input?", "a": "Yes, as part of the astronomical data linkage feature."},
    {"q": "Can users generate planets based on exoplanet data?", "a": "Yes, from databases like NASA and ESA."},
    {"q": "How does Astira prevent infinite chaotic planet generation?", "a": "By requiring a mapping relationship to the original series."},
    {"q": "What happens if a user's description is too vague?", "a": "The AI likely applies default or probabilistic interpretations, but the whitepaper does not specify exact fallback."},
    {"q": "Can users generate a planet without any story?", "a": "Yes, but story tags are part of the input to enrich the narrative."},
    {"q": "Is the AI model fine-tuned by the community?", "a": "Later, the DAO can participate in direction of AI model fine-tuning."},
    {"q": "What is a 'generation recipe'?", "a": "A set of parameters or style templates for AI generation, some of which may be rare and unlockable."},
    {"q": "Can users sell their AI generation templates?", "a": "The whitepaper does not specify, but premium generation recipes are a revenue source for the platform."},
    {"q": "Does the AI generate only planets, not other objects?", "a": "The platform focuses on planets; other cosmic objects are not mentioned."},
    {"q": "How long does AI generation take?", "a": "Not specified, but likely near real-time."},
    {"q": "Can users generate multiple versions of the same planet idea?", "a": "Yes, with premium services allowing more tries or edits."},
    {"q": "What file formats are the generated visuals?", "a": "Not specified, but typical would be PNG, GIF, or 3D model formats."},
    {"q": "Does the AI generate a planet's backstory?", "a": "It generates story tags and attributes; users may add their own logs."},
    {"q": "Can two users generate identical planets?", "a": "Unlikely due to blockchain uniqueness and rarity constraints."},
    {"q": "Is there a limit to how many planets a user can generate?", "a": "Not specified, but minting and generation fees may apply."},
    {"q": "Can the AI generate animations?", "a": "The whitepaper mentions 2D/3D visuals but not explicitly animations."},
    {"q": "What role does 'resource type' play?", "a": "It affects integration, deconstruction, and evolution possibilities."},
    {"q": "Can a user claim a planet name that already exists?", "a": "The platform likely enforces unique names or coordinates."},
    {"q": "Is there a preview before minting?", "a": "Yes, free users get basic preview."},
    {"q": "Does the AI use off-chain or on-chain computation?", "a": "AI generation is likely off-chain, with results stored on-chain or in IPFS."},
    {"q": "Can the AI generate planets in the style of specific original series?", "a": "Yes, through the gene inheritance mechanism."},
    {"q": "What is the purpose of 'energy rings' in generation?", "a": "A visual and attribute element that affects rarity and evolution."},
    {"q": "Can users input negative prompts?", "a": "Not mentioned, but likely not part of MVP."},
    {"q": "Is the AI model proprietary to Astira?", "a": "The whitepaper implies it is developed by the platform."},
    {"q": "Will the AI model improve over time?", "a": "Yes, with community input and fine-tuning."},
    {"q": "Can users generate planets collectively?", "a": "Not mentioned; likely individual creation."},
    {"q": "Does AI generation cost $AST tokens?", "a": "Premium generation does; basic preview may be free."},
    {"q": "What is a 'rarity enhancement' in AI output?", "a": "The AI can assign higher rarity based on input parameters."},
    {"q": "Can AI generate a planet that is a fusion of two real exoplanets?", "a": "Possibly through the astronomical data linkage feature."},
    {"q": "Does the AI consider user's previous planets for lineage?", "a": "Not specified; lineage is typically from original series."},
    {"q": "What is the most important aesthetic constraint?", "a": "Inheritance from the original 16 planets."},
    {"q": "Is there a manual override for AI results?", "a": "Users can edit with premium services, but not fully override the inheritance."},

    # --- Original Series & Revenue Sharing (101–150) ---
    {"q": "How many planets are in the original series?", "a": "16."},
    {"q": "What is the role of the original series?", "a": "They are the aesthetic ancestors and value source for all subsequent generations."},
    {"q": "What is the 'gene inheritance mechanism'?", "a": "New planets must have a mapping relationship to the original series in color, structure, climate, resource tags, or thematic emotions."},
    {"q": "How is revenue shared with original series holders?", "a": "When a new planet is generated based on a branch of an original series, a portion of royalties or creative earnings is automatically allocated to the corresponding rights holders."},
    {"q": "Does this revenue sharing last forever?", "a": "The whitepaper implies a continuous sharing mechanism."},
    {"q": "What happens if a new planet draws from multiple original series?", "a": "Not specified; likely split or prioritized by algorithm."},
    {"q": "Can the original series holders veto certain derivations?", "a": "Not explicitly stated, but DAO governance might allow influence."},
    {"q": "Are the original series NFTs tradeable?", "a": "Yes, they are NFTs."},
    {"q": "Do original series holders get governance rights?", "a": "Yes, they are one of the groups with governance rights."},
    {"q": "How does Astira protect the scarcity of original series?", "a": "By requiring inheritance and setting fusion/consumption requirements for high-rare original versions."},
    {"q": "Is there a cap on how many derivative planets can be made from one original?", "a": "Not specified; but scarcity is reinforced through value, not numerical cap."},
    {"q": "Can the original series planets themselves evolve?", "a": "Likely yes, as all planets have dynamic evolution."},
    {"q": "What is the benefit of holding an original series planet?", "a": "Royalty income, governance rights, and prestige."},
    {"q": "Does the platform buy back original series?", "a": "Not mentioned."},
    {"q": "Can a user create a planet that is an exact copy of an original?", "a": "No, inheritance requires mapping but not identical."},
    {"q": "How is the royalty percentage determined?", "a": "Not specified; likely set by platform or DAO."},
    {"q": "Do original series holders earn from secondary sales of derivatives?", "a": "Possibly, if royalties are configured on each sale."},
    {"q": "Is the original series fully minted at launch?", "a": "Yes, they are introduced in Phase One."},
    {"q": "Can the original series be expanded by the community?", "a": "Unlikely; they are fixed ancestors."},
    {"q": "What happens if an original series holder sells their NFT?", "a": "The new holder receives the future royalty streams."},
    {"q": "Does the revenue sharing apply to integration/deconstruction fees?", "a": "Not specified; likely only generation royalties."},
    {"q": "Are there different tiers of original series rarity?", "a": "Not specified, but likely yes."},
    {"q": "Can a derivative planet become more valuable than its original ancestor?", "a": "Possibly, through evolution and rarity enhancements."},
    {"q": "Does the platform guarantee a minimum royalty for original holders?", "a": "Not mentioned."},
    {"q": "Can original series holders propose new inheritance rules?", "a": "Through DAO governance."},
    {"q": "What is the purpose of 'cosmic genealogy'?", "a": "To show the lineage and relationship between planets."},
    {"q": "Is the genealogy visible on the galaxy map?", "a": "Likely yes."},
    {"q": "Do original planets have special visual markers?", "a": "Likely, as ancestors."},
    {"q": "Can a derivative planet become an ancestor for further derivatives?", "a": "Possibly, but the whitepaper focuses on original series as ancestors."},
    {"q": "Is there a limit on total supply of planets?", "a": "Not specified; AI generation could be unlimited but constrained by inheritance."},
    {"q": "What prevents dilution of original series value?", "a": "The royalty sharing and the fact that each derivative pays tribute."},
    {"q": "Can users buy derivative rights to an original series?", "a": "Not directly; anyone can generate based on lineage, but royalties flow to holders."},
    {"q": "Is there an approval process for lineage mapping?", "a": "The AI handles it automatically."},
    {"q": "Could an original series holder reject a specific derivative?", "a": "Not mentioned; likely not."},
    {"q": "Does the platform take a cut of the royalty?", "a": "Unclear; typical NFT platforms take a fee."},
    {"q": "Are the original series planets also dynamic?", "a": "Yes, all planets have dynamic evolution."},
    {"q": "What thematic emotions are in the original series?", "a": "Not specified; examples would be 'mysterious,' 'fiery,' 'icy,' etc."},
    {"q": "Can the original series be staked?", "a": "Likely yes, for rewards."},
    {"q": "Is there a secondary market for original series?", "a": "Yes, on the platform."},
    {"q": "How are new planets assigned to an original series branch?", "a": "By AI based on similarity in color, structure, climate, resources, or theme."},
    {"q": "If a derivative changes significantly through evolution, does it still pay royalties?", "a": "Likely yes, because its genesis lineage is recorded."},
    {"q": "Are royalties paid in $AST?", "a": "Probably, but not specified."},
    {"q": "Can a user generate a planet without any lineage?", "a": "No, all must have mapping to original series."},
    {"q": "What happens if the original series holders lose interest?", "a": "The royalty mechanism still works automatically."},
    {"q": "Is there a public registry of lineage?", "a": "Likely on-chain."},
    {"q": "Do original series planets have unique evolution paths?", "a": "Possibly, but not specified."},
    {"q": "Can the community vote to add a new original series?", "a": "Unlikely, but DAO could decide."},
    {"q": "What is the 'source of value' meaning?", "a": "The original series set the aesthetic and rarity benchmarks."},
    {"q": "Are there any original series that cannot be used for derivation?", "a": "Not specified."},
    {"q": "What happens if a derivative planet is deconstructed?", "a": "The original holder still earned the royalty at mint; deconstruction doesn't reverse that."},

    # --- Dynamic Evolution Mechanism (151–200) ---
    {"q": "What is a dynamic NFT in Astira?", "a": "A planet that changes over time, behavior, and on-chain events."},
    {"q": "How can users trigger planet evolution?", "a": "By signing in, caring for, staking, completing tasks, participating in activities, equipping resources, or triggering specific events."},
    {"q": "What possible changes can occur through evolution?", "a": "New satellites, appearance upgrades, new skins, rarity enhancements, or special statuses."},
    {"q": "What are on-chain events?", "a": "Periodic or random cosmic events set by the platform, such as comet passes, star core fissions, black hole tides, and civilization revivals."},
    {"q": "How do on-chain events affect planets?", "a": "They can change planetary attributes, increasing narrative and secondary market differentiation."},
    {"q": "What is the product value of dynamic evolution?", "a": "It transforms NFTs from 'buying ends' to 'buying begins,' increasing retention and lifecycle."},
    {"q": "Does evolution cost $AST?", "a": "Possibly, as a function fee."},
    {"q": "Can a planet's rarity decrease through evolution?", "a": "Not mentioned; likely only increases or changes laterally."},
    {"q": "What are 'new satellites'?", "a": "Moons or companion objects that appear around the planet."},
    {"q": "What are 'skins' in planet evolution?", "a": "Visual appearance upgrades."},
    {"q": "Is there a limit to how many times a planet can evolve?", "a": "Not specified."},
    {"q": "Can users choose not to evolve their planet?", "a": "Yes, evolution is triggered by user action or events."},
    {"q": "Do all planets evolve at the same rate?", "a": "No, depends on user activity and triggered events."},
    {"q": "Are evolution results random?", "a": "Partially, based on events and actions."},
    {"q": "Can a planet die or become worthless through evolution?", "a": "Not mentioned; likely always adds value or narrative."},
    {"q": "What is a 'star core fission' event?", "a": "An on-chain event that changes planet attributes."},
    {"q": "What is a 'black hole tide'?", "a": "Another cosmic event that alters planets."},
    {"q": "What is a 'civilization revival'?", "a": "An event that might boost habitability or resource attributes."},
    {"q": "Can users trigger specific events intentionally?", "a": "Some events may be triggered by user actions; others are random."},
    {"q": "Are evolution results stored on-chain?", "a": "Likely yes, as dynamic state."},
    {"q": "Does evolution affect a planet's market price?", "a": "Yes, rarity enhancements and upgrades increase value."},
    {"q": "Can a planet's evolution be reversed?", "a": "Not specified; likely not."},
    {"q": "What is 'caring for' a planet?", "a": "An interaction that may include feeding resources or regular check-ins."},
    {"q": "Does staking a planet affect evolution?", "a": "Yes, staking is one of the triggers."},
    {"q": "Can a planet evolve while it's listed for sale?", "a": "Probably yes, but might complicate ownership."},
    {"q": "Are there leaderboards for most-evolved planets?", "a": "Not specified, but possible."},
    {"q": "Can users equip resources to planets?", "a": "Yes, that can trigger evolution."},
    {"q": "Where do resources come from?", "a": "Deconstruction of other planets or rewards."},
    {"q": "Can a planet have multiple satellites?", "a": "Possibly."},
    {"q": "Do satellites have their own attributes?", "a": "Not specified."},
    {"q": "What is a 'special status'?", "a": "Temporary or permanent modifiers like 'blessed,' 'corrupted,' etc."},
    {"q": "How often do on-chain events happen?", "a": "Periodically or randomly, not specified."},
    {"q": "Can the DAO influence event frequency?", "a": "Yes, one of the governance scopes."},
    {"q": "Are event results deterministic?", "a": "Could be probabilistic."},
    {"q": "Does evolution require gas fees?", "a": "Likely yes for on-chain state changes."},
    {"q": "Can users see a planet's evolution history?", "a": "Probably through logs or on-chain history."},
    {"q": "What is a 'civilization module' in evolution?", "a": "A component that might appear from deconstruction and be used for upgrades."},
    {"q": "Can two users collaborate to evolve a planet?", "a": "Not mentioned."},
    {"q": "Does evolution affect the galaxy map display?", "a": "Likely yes, visual changes appear."},
    {"q": "Can a planet become legendary through evolution?", "a": "Rarity enhancements can increase its tier."},
    {"q": "Is there a cooldown between evolutions?", "a": "Not specified."},
    {"q": "Can evolution be sped up with $AST?", "a": "Possibly, but not stated."},
    {"q": "What happens to a planet if its owner is inactive?", "a": "It may not evolve, but on-chain events could still affect it."},
    {"q": "Are there negative evolution outcomes?", "a": "Not mentioned, likely all positive or narrative-driven."},
    {"q": "Can a planet 'die' from a black hole event?", "a": "Not specified; likely transformed, not destroyed."},
    {"q": "What is the difference between evolution and integration?", "a": "Evolution changes a single planet; integration merges two planets into a new one."},
    {"q": "Can evolution consume other assets?", "a": "It can consume equipped resources."},
    {"q": "Is there a maximum rarity level?", "a": "Not specified."},
    {"q": "Does the platform give evolution hints?", "a": "Likely through community or guides."},
    {"q": "What is the most powerful evolution trigger?", "a": "Probably special on-chain events like star core fission."},

    # --- Galaxy Map & Social Exploration (201–250) ---
    {"q": "What is the galaxy map?", "a": "A unified display of all minted planets in a browsable, interactive cosmic space."},
    {"q": "Can users navigate the galaxy map?", "a": "Yes, they can pilot their planets or identity vehicles to access other planets."},
    {"q": "What can you see on another planet's page?", "a": "Logs, stories, showcase pages, live content, activity records."},
    {"q": "What are 'identity vehicles'?", "a": "Avatars or ships users control to move through the map."},
    {"q": "Is the galaxy map fully 3D?", "a": "Lightweight 2D/light 3D approach."},
    {"q": "Why does Astira avoid a heavy metaverse?", "a": "To be more conducive to product implementation and early growth."},
    {"q": "What types of events can be held on the map?", "a": "Interstellar trade fairs, themed exhibitions, planet parties, co-branded events, brand sponsorship nodes."},
    {"q": "Can users leave comments on other planets?", "a": "Not specified, but likely social features."},
    {"q": "Is the galaxy map permissioned?", "a": "Some core areas may require DAO approval to enter."},
    {"q": "Can users hide their planet from the map?", "a": "Not mentioned."},
    {"q": "Does the map show cosmic coordinates?", "a": "Yes."},
    {"q": "Can users form alliances or clusters on the map?", "a": "Not explicitly, but possible through social exploration."},
    {"q": "What is a 'planet party'?", "a": "A social event hosted on a planet."},
    {"q": "Can users trade while on the map?", "a": "Trading activities can extend into social interactions."},
    {"q": "Is the map available on mobile?", "a": "Not specified, but likely."},
    {"q": "Can users bookmark favorite planets?", "a": "Possibly."},
    {"q": "Does the map show planet rarity visually?", "a": "Likely through visual cues."},
    {"q": "Can users send messages to planet owners?", "a": "Not specified."},
    {"q": "Are there map exploration rewards?", "a": "Not specified, but possible."},
    {"q": "Can users create their own star systems?", "a": "Not mentioned."},
    {"q": "What is a 'themed exhibition'?", "a": "An event where planets with a common theme are showcased."},
    {"q": "Can brands sponsor a star zone?", "a": "Yes, that's a future revenue model."},
    {"q": "Does the map support VR?", "a": "Not mentioned."},
    {"q": "Can users earn $AST by visiting planets?", "a": "Not specified."},
    {"q": "Are there rare planets hidden on the map?", "a": "Possibly through events."},
    {"q": "Can users set their planet to 'private'?", "a": "Not mentioned."},
    {"q": "What is a 'user log'?", "a": "A journal or activity feed attached to a planet."},
    {"q": "Can users upload images to their planet log?", "a": "Likely."},
    {"q": "Does the map have a zoom function?", "a": "Implicitly."},
    {"q": "Can users search for planets by attribute?", "a": "Likely."},
    {"q": "What is a 'co-branded event'?", "a": "An event sponsored by an external brand."},
    {"q": "Can planets move on the map?", "a": "Not mentioned; coordinates might be fixed."},
    {"q": "Is the map updated in real time?", "a": "Should be."},
    {"q": "Can users see online friends on the map?", "a": "Possibly."},
    {"q": "Does the map have a mini-map?", "a": "Not specified."},
    {"q": "Can users create temporary portals?", "a": "Not mentioned."},
    {"q": "What is the strategic significance of the lightweight map?", "a": "Cheaper to build and scale, more accessible."},
    {"q": "Can users embed external links on their planet page?", "a": "Not specified."},
    {"q": "Is there a global chat on the map?", "a": "Not specified."},
    {"q": "Can users host live streams from their planet?", "a": "Live content is mentioned, so yes."},
    {"q": "Are there NPCs or cosmic creatures?", "a": "Not mentioned."},
    {"q": "Can users trade planet resources directly on the map?", "a": "Possibly through trade fairs."},
    {"q": "Does the map have day/night cycles?", "a": "Not specified."},
    {"q": "Can users form fleets?", "a": "Not mentioned."},
    {"q": "What is the 'interstellar trade fair'?", "a": "An event where users can trade planets and resources."},
    {"q": "Can users rate other planets?", "a": "Possibly, but not specified."},
    {"q": "Is the galaxy map a core retention feature?", "a": "Yes, it increases user engagement time."},
    {"q": "Can a planet become a landmark on the map?", "a": "Likely if highly rare or evolved."},
    {"q": "Does the map show real-time astronomical data?", "a": "Not for all planets, only those linked to data."},
    {"q": "Can users mint new planets directly from the map interface?", "a": "Possibly, but not detailed."},

    # --- Integration, Deconstruction & Circular Economy (251–300) ---
    {"q": "What is the integration mechanism?", "a": "Users can merge two planet NFTs to generate a brand new hybrid planet."},
    {"q": "What happens to the original two planets after integration?", "a": "They are burned, locked, or consumed."},
    {"q": "Does the new planet inherit attributes?", "a": "Yes, it inherits original attributes and stacks rare bonuses."},
    {"q": "What is the deconstruction mechanism?", "a": "Breaking a planet into resource fragments, star cores, mineral cards, or civilization modules."},
    {"q": "Can deconstructed fragments be traded?", "a": "Yes, individually."},
    {"q": "Can fragments be used later?", "a": "Yes, for reorganizing or upgrading other planets."},
    {"q": "What is the circular value of these mechanisms?", "a": "Creates a multi-layer cycle: generation, cultivation, integration, deconstruction, re-trading."},
    {"q": "How does integration affect original series scarcity?", "a": "High-rare original versions may require fusion consumption or locking, reinforcing value."},
    {"q": "Does integration require $AST?", "a": "Likely yes, as a function fee."},
    {"q": "Can a hybrid planet be deconstructed again?", "a": "Probably yes."},
    {"q": "What is a 'star core'?", "a": "A rare fragment from deconstruction."},
    {"q": "What is a 'mineral card'?", "a": "A tradeable resource fragment."},
    {"q": "What is a 'civilization module'?", "a": "A component that could be used for upgrades."},
    {"q": "Can fragments be combined to form a new planet?", "a": "Possibly through a reconstruction feature."},
    {"q": "Does integration always produce a better planet?", "a": "Not necessarily, but it stacks rare bonuses."},
    {"q": "Can more than two planets be integrated at once?", "a": "Not specified."},
    {"q": "Is there a limit on how many times a planet can be integrated?", "a": "Each integration consumes the inputs, so a new planet is a fresh entity."},
    {"q": "Can a user deconstruct a planet they just bought?", "a": "Yes, at their discretion."},
    {"q": "What happens to the planet's evolution history after integration?", "a": "It's replaced by the new planet's history."},
    {"q": "Does deconstruction destroy the NFT?", "a": "Yes, it is broken into fragments."},
    {"q": "Are fragments stored on-chain?", "a": "Likely as separate tokens."},
    {"q": "Can fragments be used as currency?", "a": "Possibly within the ecosystem."},
    {"q": "Does integration consume $AST as well as planets?", "a": "The whitepaper says 'set to burn, lock, or consume resources' – resources may include $AST."},
    {"q": "Can a user integrate a planet with a fragment?", "a": "Not directly; integration is planet+planet."},
    {"q": "What is the purpose of 'locking' instead of burning?", "a": "Locking could allow future retrieval or temporary consumption."},
    {"q": "Does the platform take a fee for integration?", "a": "Yes, as a function fee."},
    {"q": "Can the DAO change integration rules?", "a": "Yes."},
    {"q": "Are there achievements for integration?", "a": "Not specified."},
    {"q": "Can a hybrid planet be an ancestor for new derivatives?", "a": "Possibly, but lineage would be complex."},
    {"q": "What happens to royalties when a derivative is integrated?", "a": "The original royalties were already paid at mint; integration doesn't reverse."},
    {"q": "Can deconstruction be undone?", "a": "No, unless fragments are reassembled."},
    {"q": "Are there rare fragments that only drop from legendary planets?", "a": "Likely."},
    {"q": "Can fragments be used in evolution?", "a": "Yes, as resources."},
    {"q": "What is the most valuable fragment type?", "a": "Star core or civilization module."},
    {"q": "Can users list fragments on the marketplace?", "a": "Yes."},
    {"q": "Does integration increase total NFT supply?", "a": "No, it replaces two with one, reducing supply."},
    {"q": "Does deconstruction increase total NFT supply?", "a": "No, it replaces one with multiple fragments (non-NFT tokens?)."},
    {"q": "Are fragments considered NFTs or fungible tokens?", "a": "Likely semi-fungible or ERC-1155."},
    {"q": "Can fragments be staked?", "a": "Not specified."},
    {"q": "What is the 'lock' period for integration?", "a": "Not specified."},
    {"q": "Can a user cancel an integration before completion?", "a": "Not specified."},
    {"q": "Does integration require both planets to be owned by the same user?", "a": "Yes, unless the platform allows partnerships."},
    {"q": "Can a user integrate a planet with a pending evolution?", "a": "Possibly not."},
    {"q": "Are there visual changes after deconstruction?", "a": "The planet disappears; fragments have their own icons."},
    {"q": "Can fragments be used to enter special events?", "a": "Possibly."},
    {"q": "Is there a marketplace specifically for fragments?", "a": "Likely part of the main trading market."},
    {"q": "Can a user deconstruct a planet and then use its fragments to upgrade another planet?", "a": "Yes."},
    {"q": "Does integration have a cooldown?", "a": "Not specified."},
    {"q": "Can a planet be both evolved and integrated?", "a": "Integration is separate; evolution happens before or after."},
    {"q": "What is the economic benefit of deconstruction?", "a": "It creates liquidity and resources for further upgrades."},

    # --- Real Astronomical Data Linkage (301–350) ---
    {"q": "What external data sources does Astira use?", "a": "NASA and ESA public astronomical databases."},
    {"q": "What kind of parameters can users reference?", "a": "Orbital period, mass, temperature, star type, topographical assumptions."},
    {"q": "What is a 'scientific artistic' planet NFT?", "a": "A planet generated based on real exoplanet parameters."},
    {"q": "Does Astira hold 'Discover New Planets' activities?", "a": "Yes, regularly."},
    {"q": "Who votes on the best scientific-artistic planets?", "a": "The community."},
    {"q": "What are the rewards for winners?", "a": "Airdrops, exposure, or revenue incentives."},
    {"q": "Can users submit real exoplanet data not in the databases?", "a": "Not specified."},
    {"q": "Does the astronomical data update automatically?", "a": "Likely periodically."},
    {"q": "Can a user generate a planet from a specific known exoplanet (e.g., Proxima b)?", "a": "Yes."},
    {"q": "Is there an educational component?", "a": "Yes, to attract astronomy enthusiasts and science organizations."},
    {"q": "Can schools use Astira for educational projects?", "a": "Possibly through partnerships."},
    {"q": "Does Astira collaborate with scientific institutions?", "a": "The whitepaper suggests potential partnerships."},
    {"q": "Can users add their own astronomical observations?", "a": "Not mentioned."},
    {"q": "Are there leaderboards for scientific accuracy?", "a": "Not specified."},
    {"q": "Does the platform verify scientific parameters?", "a": "They come from official databases."},
    {"q": "Can a user generate a planet based on a hypothetical star?", "a": "Yes, using natural language without real data."},
    {"q": "What is the benefit of using real data?", "a": "Cross-industry value, attracting wider audience."},
    {"q": "Can real-data planets have special badges?", "a": "Likely."},
    {"q": "Are there separate rarity tiers for real-data planets?", "a": "Not specified."},
    {"q": "Does Astira have a partnership with NASA?", "a": "No, it uses public data."},
    {"q": "Can users mint a planet that is an exact match of a known exoplanet?", "a": "The AI generates artistic interpretations."},
    {"q": "Is the astronomical data linkage available at launch?", "a": "It's part of ecological expansion (Phase Three)."},
    {"q": "Can the DAO add new data sources?", "a": "Possibly."},
    {"q": "Are there contests for best fictional planet based on real data?", "a": "Yes, 'Discover New Planets.'"},
    {"q": "Can users sell their scientifically accurate planets at higher prices?", "a": "Market determines value."},
    {"q": "Does Astira provide educational content about exoplanets?", "a": "Likely through blog or activities."},
    {"q": "Can users generate a planet of a black hole?", "a": "Not mentioned; black holes are events, not planets."},
    {"q": "What is 'topographical assumption'?", "a": "AI-generated terrain based on real data constraints."},
    {"q": "Can real-data planets evolve differently?", "a": "Not specified, but likely same mechanisms."},
    {"q": "Will there be a category filter for real-data planets?", "a": "Probably."},
    {"q": "Can users merge a real-data planet with a fantasy planet?", "a": "Yes, integration works regardless."},
    {"q": "Does Astira issue certificates of scientific inspiration?", "a": "Not mentioned."},
    {"q": "Can the community vote to add a specific exoplanet to a featured list?", "a": "Possibly through DAO."},
    {"q": "Are real-data planets more likely to be rare?", "a": "Not inherently."},
    {"q": "Does the platform have a library of real exoplanet names?", "a": "Likely."},
    {"q": "Can users rename a real-data planet?", "a": "After minting, renaming may be a paid function."},
    {"q": "Is there a limit on how many real-data planets can be minted?", "a": "No."},
    {"q": "Do real-data planets have fixed coordinates?", "a": "They have cosmic coordinates in the map."},
    {"q": "Can users suggest new astronomical data sources?", "a": "Through governance."},
    {"q": "What is the educational partnership potential?", "a": "To attract science museums, planetariums, etc."},
    {"q": "Can real-data planets be used in scientific papers?", "a": "Unlikely, they are artistic."},
    {"q": "Does Astira have a scientific advisor?", "a": "Not mentioned."},
    {"q": "Can users generate a planet from an asteroid?", "a": "Possibly, as planets are the focus."},
    {"q": "What is the most popular real exoplanet for generation?", "a": "Not specified."},
    {"q": "Does the platform have a 'random real exoplanet' button?", "a": "Not specified."},
    {"q": "Can users filter map by real-data planets?", "a": "Likely."},
    {"q": "Are there special events for real-data planet holders?", "a": "Possibly."},
    {"q": "Can a real-data planet be deconstructed for unique fragments?", "a": "Possibly."},
    {"q": "Does the astronomical data linkage include star types?", "a": "Yes."},
    {"q": "What is the long-term vision for this feature?", "a": "To expand Astira's audience beyond NFT community into science and education."},

    # --- DAO Governance & Planetary Council (351–400) ---
    {"q": "Who gets governance rights in Astira?", "a": "Holders of original series NFTs, qualified planet holders, and AST token holders."},
    {"q": "What can the DAO decide?", "a": "Feature priorities, activity rules, frequency of rare events, AI model fine-tuning direction, map core area access standards, ecological incentive distribution."},
    {"q": "What is the 'Planetary Council'?", "a": "The later-stage community-driven governance body."},
    {"q": "How does governance transition over time?", "a": "From platform-led to joint governance to community-led."},
    {"q": "Is DAO just a voting button?", "a": "No, it gives users lasting influence over the cosmic order."},
    {"q": "Can any planet holder vote?", "a": "Only 'qualified' planet holders – criteria not specified."},
    {"q": "Does the DAO control the treasury?", "a": "Probably, through incentive distribution."},
    {"q": "Can the DAO change royalty percentages?", "a": "Likely, as part of economic parameters."},
    {"q": "How are proposals submitted?", "a": "Through the DAO proposal system (Phase Three)."},
    {"q": "Is there a minimum token holding for voting?", "a": "Not specified."},
    {"q": "Can the DAO veto a brand partnership?", "a": "Possibly, depending on governance scope."},
    {"q": "What happens if the DAO is inactive?", "a": "Platform may retain temporary control."},
    {"q": "Can the DAO propose new planet types?", "a": "Yes, AI model fine-tuning."},
    {"q": "Is there a veto power by the core team?", "a": "In early stages, platform-led governance."},
    {"q": "Can the DAO adjust transaction fees?", "a": "Possibly."},
    {"q": "Are governance votes on-chain?", "a": "Likely."},
    {"q": "Can users delegate their votes?", "a": "Not specified, but common in DAOs."},
    {"q": "How often are votes held?", "a": "Not specified."},
    {"q": "Can the DAO create sub-committees?", "a": "Possibly."},
    {"q": "What is the first major governance decision?", "a": "Not specified; likely event frequency or feature priority."},
    {"q": "Do original series holders have more voting power?", "a": "Not specified, but likely weighted by asset value."},
    {"q": "Can the DAO change the tokenomics?", "a": "Within limits."},
    {"q": "Is there a governance token separate from $AST?", "a": "No, $AST is used for governance."},
    {"q": "Can the DAO decide to burn tokens?", "a": "Possibly."},
    {"q": "What is the 'core area entry standard'?", "a": "Which areas of the galaxy map require permission."},
    {"q": "Can the DAO create new events?", "a": "Yes, activity rules."},
    {"q": "Is there a bug bounty or DAO-controlled development fund?", "a": "Not specified."},
    {"q": "Can the DAO expel a user?", "a": "Unlikely."},
    {"q": "How are DAO members identified?", "a": "By wallet address holding qualifying assets."},
    {"q": "Can a user earn voting power by staking?", "a": "Staking for rewards is mentioned, not explicitly for voting, but likely."},
    {"q": "What is the quorum for a vote?", "a": "Not specified."},
    {"q": "Can the DAO change the AI generation constraints?", "a": "Yes, through fine-tuning direction."},
    {"q": "Is there a DAO treasury address?", "a": "Likely."},
    {"q": "Can the DAO fund community projects?", "a": "Ecological incentive distribution."},
    {"q": "What prevents a whale from controlling the DAO?", "a": "Not specified; may use quadratic voting or other mechanisms."},
    {"q": "Can the DAO propose a hard fork?", "a": "Unlikely at early stage."},
    {"q": "Are governance discussions held on a forum?", "a": "Probably."},
    {"q": "Can the DAO adjust the rarity event frequency?", "a": "Yes."},
    {"q": "Does the DAO have control over the Astira Chain launch?", "a": "Possibly in later phases."},
    {"q": "Can the DAO add new revenue streams?", "a": "Through feature priorities."},
    {"q": "What is the role of the Planetary Council compared to general DAO?", "a": "Council may be a smaller elected body."},
    {"q": "Can the DAO impeach the core team?", "a": "Unlikely; not mentioned."},
    {"q": "Are there term limits for council members?", "a": "Not specified."},
    {"q": "Can the DAO set the inflation rate of $AST?", "a": "Possibly, but token distribution is fixed initially."},
    {"q": "Can the DAO decide to airdrop to specific groups?", "a": "Yes, incentive distribution."},
    {"q": "Does the DAO have access to platform analytics?", "a": "Likely."},
    {"q": "Can the DAO create its own sub-tokens?", "a": "Not mentioned."},
    {"q": "What is the most powerful DAO ability?", "a": "AI model fine-tuning and event frequency."},
    {"q": "Can the DAO blacklist certain planets?", "a": "Unlikely."},
    {"q": "Is DAO participation rewarded with $AST?", "a": "Possibly through incentive distribution."},

    # --- Business Model & Revenue (401–450) ---
    {"q": "What is the most direct revenue source?", "a": "Transaction fees from primary and secondary NFT sales."},
    {"q": "Does Astira charge for AI generation?", "a": "Premium generation services are paid; basic preview free."},
    {"q": "What are examples of AI premium services?", "a": "Higher precision, richer style templates, more editing opportunities, rare generation recipes."},
    {"q": "What are minting and function fees?", "a": "Fees for minting, fusion, disassembly, renaming, skin upgrades, special event activation."},
    {"q": "How does brand partnership revenue work?", "a": "Advertising space on planet surfaces, sponsoring star zones, co-branded planet sales, themed exhibitions."},
    {"q": "Will the platform have paid skin upgrades?", "a": "Yes, as function fees."},
    {"q": "Can users avoid fees by not evolving?", "a": "Yes, but evolution may increase value."},
    {"q": "Does Astira take a cut from royalties paid to original holders?", "a": "Not specified, but typical platforms take a percentage."},
    {"q": "What is a 'rare generation recipe'?", "a": "A paid template that produces rarer planets."},
    {"q": "Are transaction fees flat or percentage?", "a": "Not specified; likely percentage."},
    {"q": "Can the DAO change fee structures?", "a": "Possibly."},
    {"q": "Does Astira have a subscription model?", "a": "No, only pay-per-use."},
    {"q": "What is a 'co-branded planet sale'?", "a": "Selling planets designed in collaboration with a brand."},
    {"q": "Can brands sponsor a star zone?", "a": "Yes, a future revenue model."},
    {"q": "Are there fees for listing on the marketplace?", "a": "Not specified, but transaction fees cover sales."},
    {"q": "Does Astira earn from advertising on the galaxy map?", "a": "Future commercial interfaces may open."},
    {"q": "What is the expected split between fee types?", "a": "Not specified."},
    {"q": "Can users pay fees with $AST or only with SOL/ETH?", "a": "$AST is used for payments."},
    {"q": "Does Astira plan to have an in-app currency?", "a": "$AST is the functional token."},
    {"q": "Are there discounts for using $AST to pay fees?", "a": "Not specified."},
    {"q": "How much are typical minting fees?", "a": "Not specified."},
    {"q": "Does the platform have a fee-sharing program for referrers?", "a": "Not mentioned."},
    {"q": "Can users earn revenue by hosting events?", "a": "Possibly, but not detailed."},
    {"q": "Does Astira take fees from deconstructed fragment sales?", "a": "Transaction fees apply."},
    {"q": "What is the business model's key advantage?", "a": "Multiple, diversified streams."},
    {"q": "Will there be a launchpad for other NFT projects?", "a": "Not mentioned."},
    {"q": "Can brands buy planet advertising space permanently?", "a": "Likely temporary sponsorship."},
    {"q": "Does Astira plan to have a premium membership?", "a": "Not mentioned; premium is per generation."},
    {"q": "Are fees higher for rare planet minting?", "a": "Not specified."},
    {"q": "Does the platform offer bulk minting discounts?", "a": "Not specified."},
    {"q": "Can users pay fees with credit card?", "a": "Not mentioned; likely crypto only."},
    {"q": "What is the 'function fee' for special event activation?", "a": "Fee to trigger an event or participate."},
    {"q": "How does Astira ensure fee transparency?", "a": "Not specified, but on-chain fees are visible."},
    {"q": "Can the platform survive on transaction fees alone?", "a": "Possibly, but diversified is safer."},
    {"q": "Are there any free features besides preview?", "a": "Browsing map, viewing planets."},
    {"q": "Does Astira take a fee from integration?", "a": "Yes, as a function fee."},
    {"q": "What is the typical transaction fee percentage in NFT marketplaces?", "a": "2-5%; not specified for Astira."},
    {"q": "Can users negotiate fees?", "a": "No."},
    {"q": "Does Astira charge for renaming a planet?", "a": "Yes, as a function fee."},
    {"q": "Are there fees for transferring planets between wallets?", "a": "Standard gas + possibly platform fee."},
    {"q": "Does Astira take a cut of staking rewards?", "a": "Not specified."},
    {"q": "What is the 'skin upgrade' fee?", "a": "Cost to change visual appearance."},
    {"q": "Can users earn fee discounts through loyalty?", "a": "Not specified."},
    {"q": "Does the platform have a burn mechanism for fees?", "a": "Not mentioned."},
    {"q": "How does Astira compete with zero-fee platforms?", "a": "By offering unique features like evolution and AI."},
    {"q": "Are there fees for DAO proposal submission?", "a": "Not specified."},
    {"q": "Can brands sponsor a planet's evolution?", "a": "Possibly through brand partnerships."},
    {"q": "What is the most innovative revenue source?", "a": "Planet surface advertising."},
    {"q": "Does Astira plan to offer API access for a fee?", "a": "Later with developer interfaces."},
    {"q": "Is there a fee to join the Planetary Council?", "a": "No, it's governance-based."},

    # --- Tokenomics ($AST) (451–500) ---
    {"q": "What is $AST?", "a": "The core functional token of the Astira ecosystem."},
    {"q": "What are the main uses of $AST?", "a": "Paying casting fees, premium generation services, DAO governance, staking for rewards, participating in special events, unlocking rare creation permissions, ecological transactions."},
    {"q": "Does $AST have a fixed supply?", "a": "The distribution percentages are given, but total supply not specified."},
    {"q": "What is the token distribution?", "a": "Ecological Development 25%, Team 20%, Community Incentives 20%, Liquidity 15%, Marketing 10%, Airdrop 10%."},
    {"q": "Is there a vesting schedule for team tokens?", "a": "Not specified, but typical for projects."},
    {"q": "Can $AST be mined or earned?", "a": "Through community incentives and staking."},
    {"q": "What is the value capture mechanism?", "a": "As platform activity increases, $AST usage frequency rises, creating positive correlation with demand."},
    {"q": "Is $AST designed for speculation?", "a": "No, it focuses on real functional use, long-term incentive release, and value return."},
    {"q": "Can $AST be used to pay for integration fees?", "a": "Yes, as a functional token."},
    {"q": "Does $AST have a burn mechanism?", "a": "Not explicitly stated."},
    {"q": "Can $AST be staked for governance power?", "a": "Yes, staking for rewards and governance."},
    {"q": "What is the airdrop allocation for?", "a": "10% of total supply."},
    {"q": "Who receives the airdrop?", "a": "Not specified; likely early users or original holders."},
    {"q": "Is $AST required to mint a planet?", "a": "Casting fees are paid in $AST."},
    {"q": "Can $AST be traded on external exchanges?", "a": "Likely yes, after liquidity is provided."},
    {"q": "What is the role of $AST in DAO governance?", "a": "Holders have voting rights."},
    {"q": "Does $AST have an inflation rate?", "a": "Not specified; community incentives may release new tokens."},
    {"q": "Can $AST be locked for higher rewards?", "a": "Possibly."},
    {"q": "Is there a minimum $AST balance for certain features?", "a": "Not specified."},
    {"q": "Can users earn $AST by deconstructing planets?", "a": "Not directly; they earn fragments, not $AST."},
    {"q": "What is the 'rare creation permission' unlocked by $AST?", "a": "Access to generate limited-edition or high-rarity planets."},
    {"q": "Does $AST have a max supply cap?", "a": "Not specified."},
    {"q": "Can $AST be used to buy planet NFTs directly?", "a": "Yes, as a medium for ecological transactions."},
    {"q": "Is there a treasury wallet for $AST?", "a": "Ecological Development (25%) likely."},
    {"q": "Can $AST be used to bribe voters?", "a": "Not intended, but possible in DAOs."},
    {"q": "Does $AST have a deflationary mechanism?", "a": "Not mentioned."},
    {"q": "How does a user get $AST initially?", "a": "Airdrop, purchase on DEX, or earn through community incentives."},
    {"q": "What is the marketing allocation used for?", "a": "10% for promotions, partnerships."},
    {"q": "Can the DAO change token distribution?", "a": "Possibly, but initial distribution is fixed."},
    {"q": "Is $AST an ERC-20 or SPL token?", "a": "Depends on initial chain (Solana would be SPL)."},
    {"q": "Can $AST be bridged to Astira Chain later?", "a": "Likely."},
    {"q": "What happens to unused $AST?", "a": "Held by users."},
    {"q": "Can $AST be used to pay for storage fees?", "a": "Not specified."},
    {"q": "Is there a lock-up period for team tokens?", "a": "Not specified, but typical."},
    {"q": "Does $AST give access to exclusive events?", "a": "Yes, special events may require $AST."},
    {"q": "Can $AST be lent or borrowed?", "a": "Not mentioned."},
    {"q": "What is the 'ecological transaction' medium meaning?", "a": "Trading resources, fragments, or services."},
    {"q": "Does $AST have a governance minimum threshold?", "a": "Not specified."},
    {"q": "Can users earn $AST by completing tasks?", "a": "Yes, community incentives."},
    {"q": "Is $AST required to list a planet for sale?", "a": "Not specified; likely only transaction fee."},
    {"q": "Can $AST be used to tip other users?", "a": "Not mentioned."},
    {"q": "What prevents $AST price manipulation?", "a": "Not specified; depends on liquidity."},
    {"q": "Does the platform buy back $AST?", "a": "Not mentioned."},
    {"q": "Can $AST be staked for a share of transaction fees?", "a": "Possibly, but not detailed."},
    {"q": "Is there a penalty for unstaking early?", "a": "Not specified."},
    {"q": "Can $AST be used to vote on planet naming?", "a": "Not a governance scope."},
    {"q": "What is the most important design principle of $AST?", "a": "Avoid single investment scenario, balance functional use and incentives."},
    {"q": "Does $AST have a whitepaper of its own?", "a": "No, included in Astira whitepaper."},
    {"q": "Can $AST be used to sponsor a planet party?", "a": "Possibly as event participation fee."},
    {"q": "What is the ultimate goal of the $AST token model?", "a": "To align platform activity with token demand, creating a sustainable ecosystem."},
]


def find_answer(question):
    """Simple keyword‑based search. Returns the best matching answer."""
    if not question or not question.strip():
        return "I'm sorry, I didn't understand that question. Could you rephrase?"
    question_words = set(re.findall(r'\w+', question.lower()))
    best_score = 0
    best_answer = None
    for item in QA_DATA:
        item_words = set(re.findall(r'\w+', item["q"].lower()))
        score = len(question_words & item_words)
        if score > best_score:
            best_score = score
            best_answer = item["a"]
    if best_score == 0:
        return "I'm sorry, I didn't understand that question. Could you rephrase? You can also check the FAQ section below."
    return best_answer
